import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { deleteEverything, setupDefaultLists } from "../actions/actions";
import getServerSession from "next-auth";
import SessionProvider from "@/components/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "uNote",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-white`}>
        {children}
      </body>
    </html>
  );
}
